### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by milanchx** [Amb1tion/Patrician-Bot#6]
So my friend wanted to link his last.fm account with the bot last night and the bot keeps returning the _"list index out of range"_ error. I tried linking his last.fm with my discord, but it didn't work either.

![image](https://user-images.githubusercontent.com/64268581/81472241-fb296d80-91f6-11ea-91be-4dbb859db7af.png)

**Comment by Amb1tion** [comment]
Thank You for bringing this to my attention, that was because of poor error handling. Your friend's account is new so the bot has nothing to show for in the output, it will now inform users that you need to have scrobbled 2 tracks to make use of the fm command.
![image](https://user-images.githubusercontent.com/28458651/81487861-353c5300-927b-11ea-8bec-e6777c610122.png)
